### PR TITLE
Add static files and GitHub action for SophieBot.Web

### PR DESCRIPTION
**Pull request by jimmidier**

### CODE REVIEW

**Comment by jimmidier** [comment]
Related to [https://trello.com/c/IyLJ06WE](url) and [https://trello.com/c/UIM4eaQO](url)

**Review by PatrickZhao1989 — CHANGES_REQUESTED** [review]
1. Add a readme 
2. In readme, include the command on how to generate index.min.js
3. Reference other js files from CDN instead of pulling down the js file, so that the version numbers are included

**Review by PatrickZhao1989 — APPROVED** [review]
Good work, if you use yarn then in future don't commit package-lock.json. 
Also, check with Patrick on how to better improve the github workflow with yarn

**Comment by PatrickZhao1989** [comment]
[DevOps - static website](https://trello.com/c/UIM4eaQO/3-devops-static-website)

**Pull request merged**
